"use strict";
// This file is automatically generated based on the Looker Core API metadata.
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataWebhookPayloadType = void 0;
var DataWebhookPayloadType;
(function (DataWebhookPayloadType) {
    DataWebhookPayloadType["Cell"] = "cell";
    DataWebhookPayloadType["Query"] = "query";
    DataWebhookPayloadType["Dashboard"] = "dashboard";
})(DataWebhookPayloadType = exports.DataWebhookPayloadType || (exports.DataWebhookPayloadType = {}));
