"use strict";
// This file is automatically generated based on the Looker Core API metadata.
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataWebhookPayloadScheduledPlanType = void 0;
var DataWebhookPayloadScheduledPlanType;
(function (DataWebhookPayloadScheduledPlanType) {
    DataWebhookPayloadScheduledPlanType["Look"] = "Look";
    DataWebhookPayloadScheduledPlanType["Dashboard"] = "Dashboard";
})(DataWebhookPayloadScheduledPlanType = exports.DataWebhookPayloadScheduledPlanType || (exports.DataWebhookPayloadScheduledPlanType = {}));
