"use strict";
// This file is automatically generated based on the Looker Core API metadata.
Object.defineProperty(exports, "__esModule", { value: true });
exports.IntegrationSupportedVisualizationFormattings = exports.IntegrationSupportedFormattings = exports.IntegrationSupportedFormats = exports.IntegrationSupportedDownloadSettings = exports.IntegrationSupportedActionTypes = void 0;
var IntegrationSupportedActionTypes;
(function (IntegrationSupportedActionTypes) {
    IntegrationSupportedActionTypes["Cell"] = "cell";
    IntegrationSupportedActionTypes["Query"] = "query";
    IntegrationSupportedActionTypes["Dashboard"] = "dashboard";
})(IntegrationSupportedActionTypes = exports.IntegrationSupportedActionTypes || (exports.IntegrationSupportedActionTypes = {}));
var IntegrationSupportedDownloadSettings;
(function (IntegrationSupportedDownloadSettings) {
    IntegrationSupportedDownloadSettings["Push"] = "push";
    IntegrationSupportedDownloadSettings["Url"] = "url";
})(IntegrationSupportedDownloadSettings = exports.IntegrationSupportedDownloadSettings || (exports.IntegrationSupportedDownloadSettings = {}));
var IntegrationSupportedFormats;
(function (IntegrationSupportedFormats) {
    IntegrationSupportedFormats["Txt"] = "txt";
    IntegrationSupportedFormats["Csv"] = "csv";
    IntegrationSupportedFormats["InlineJson"] = "inline_json";
    IntegrationSupportedFormats["Json"] = "json";
    IntegrationSupportedFormats["JsonLabel"] = "json_label";
    IntegrationSupportedFormats["JsonDetail"] = "json_detail";
    IntegrationSupportedFormats["JsonDetailLiteStream"] = "json_detail_lite_stream";
    IntegrationSupportedFormats["Xlsx"] = "xlsx";
    IntegrationSupportedFormats["Html"] = "html";
    IntegrationSupportedFormats["WysiwygPdf"] = "wysiwyg_pdf";
    IntegrationSupportedFormats["AssembledPdf"] = "assembled_pdf";
    IntegrationSupportedFormats["WysiwygPng"] = "wysiwyg_png";
    IntegrationSupportedFormats["CsvZip"] = "csv_zip";
})(IntegrationSupportedFormats = exports.IntegrationSupportedFormats || (exports.IntegrationSupportedFormats = {}));
var IntegrationSupportedFormattings;
(function (IntegrationSupportedFormattings) {
    IntegrationSupportedFormattings["Formatted"] = "formatted";
    IntegrationSupportedFormattings["Unformatted"] = "unformatted";
})(IntegrationSupportedFormattings = exports.IntegrationSupportedFormattings || (exports.IntegrationSupportedFormattings = {}));
var IntegrationSupportedVisualizationFormattings;
(function (IntegrationSupportedVisualizationFormattings) {
    IntegrationSupportedVisualizationFormattings["Apply"] = "apply";
    IntegrationSupportedVisualizationFormattings["Noapply"] = "noapply";
})(IntegrationSupportedVisualizationFormattings = exports.IntegrationSupportedVisualizationFormattings || (exports.IntegrationSupportedVisualizationFormattings = {}));
