"use strict";
// This file is automatically generated based on the Looker Core API metadata.
Object.defineProperty(exports, "__esModule", { value: true });
exports.LookmlModelExploreFieldWeekStartDay = exports.LookmlModelExploreFieldUserAttributeFilterTypes = exports.LookmlModelExploreFieldFillStyle = exports.LookmlModelExploreFieldCategory = exports.LookmlModelExploreFieldAlign = void 0;
var LookmlModelExploreFieldAlign;
(function (LookmlModelExploreFieldAlign) {
    LookmlModelExploreFieldAlign["Left"] = "left";
    LookmlModelExploreFieldAlign["Right"] = "right";
})(LookmlModelExploreFieldAlign = exports.LookmlModelExploreFieldAlign || (exports.LookmlModelExploreFieldAlign = {}));
var LookmlModelExploreFieldCategory;
(function (LookmlModelExploreFieldCategory) {
    LookmlModelExploreFieldCategory["Parameter"] = "parameter";
    LookmlModelExploreFieldCategory["Filter"] = "filter";
    LookmlModelExploreFieldCategory["Measure"] = "measure";
    LookmlModelExploreFieldCategory["Dimension"] = "dimension";
})(LookmlModelExploreFieldCategory = exports.LookmlModelExploreFieldCategory || (exports.LookmlModelExploreFieldCategory = {}));
var LookmlModelExploreFieldFillStyle;
(function (LookmlModelExploreFieldFillStyle) {
    LookmlModelExploreFieldFillStyle["Enumeration"] = "enumeration";
    LookmlModelExploreFieldFillStyle["Range"] = "range";
})(LookmlModelExploreFieldFillStyle = exports.LookmlModelExploreFieldFillStyle || (exports.LookmlModelExploreFieldFillStyle = {}));
var LookmlModelExploreFieldUserAttributeFilterTypes;
(function (LookmlModelExploreFieldUserAttributeFilterTypes) {
    LookmlModelExploreFieldUserAttributeFilterTypes["AdvancedFilterString"] = "advanced_filter_string";
    LookmlModelExploreFieldUserAttributeFilterTypes["AdvancedFilterNumber"] = "advanced_filter_number";
    LookmlModelExploreFieldUserAttributeFilterTypes["AdvancedFilterDatetime"] = "advanced_filter_datetime";
    LookmlModelExploreFieldUserAttributeFilterTypes["String"] = "string";
    LookmlModelExploreFieldUserAttributeFilterTypes["Number"] = "number";
    LookmlModelExploreFieldUserAttributeFilterTypes["Datetime"] = "datetime";
    LookmlModelExploreFieldUserAttributeFilterTypes["RelativeUrl"] = "relative_url";
    LookmlModelExploreFieldUserAttributeFilterTypes["Yesno"] = "yesno";
    LookmlModelExploreFieldUserAttributeFilterTypes["Zipcode"] = "zipcode";
})(LookmlModelExploreFieldUserAttributeFilterTypes = exports.LookmlModelExploreFieldUserAttributeFilterTypes || (exports.LookmlModelExploreFieldUserAttributeFilterTypes = {}));
var LookmlModelExploreFieldWeekStartDay;
(function (LookmlModelExploreFieldWeekStartDay) {
    LookmlModelExploreFieldWeekStartDay["Monday"] = "monday";
    LookmlModelExploreFieldWeekStartDay["Tuesday"] = "tuesday";
    LookmlModelExploreFieldWeekStartDay["Wednesday"] = "wednesday";
    LookmlModelExploreFieldWeekStartDay["Thursday"] = "thursday";
    LookmlModelExploreFieldWeekStartDay["Friday"] = "friday";
    LookmlModelExploreFieldWeekStartDay["Saturday"] = "saturday";
    LookmlModelExploreFieldWeekStartDay["Sunday"] = "sunday";
})(LookmlModelExploreFieldWeekStartDay = exports.LookmlModelExploreFieldWeekStartDay || (exports.LookmlModelExploreFieldWeekStartDay = {}));
