"use strict";
// This file is automatically generated based on the Looker Core API metadata.
Object.defineProperty(exports, "__esModule", { value: true });
exports.LookmlModelExploreFieldTimeIntervalName = void 0;
var LookmlModelExploreFieldTimeIntervalName;
(function (LookmlModelExploreFieldTimeIntervalName) {
    LookmlModelExploreFieldTimeIntervalName["Day"] = "day";
    LookmlModelExploreFieldTimeIntervalName["Hour"] = "hour";
    LookmlModelExploreFieldTimeIntervalName["Minute"] = "minute";
    LookmlModelExploreFieldTimeIntervalName["Second"] = "second";
    LookmlModelExploreFieldTimeIntervalName["Millisecond"] = "millisecond";
    LookmlModelExploreFieldTimeIntervalName["Microsecond"] = "microsecond";
    LookmlModelExploreFieldTimeIntervalName["Week"] = "week";
    LookmlModelExploreFieldTimeIntervalName["Month"] = "month";
    LookmlModelExploreFieldTimeIntervalName["Year"] = "year";
})(LookmlModelExploreFieldTimeIntervalName = exports.LookmlModelExploreFieldTimeIntervalName || (exports.LookmlModelExploreFieldTimeIntervalName = {}));
