"use strict";
// This file is automatically generated based on the Looker Core API metadata.
Object.defineProperty(exports, "__esModule", { value: true });
exports.LookmlModelExploreFieldMapLayerFormat = void 0;
var LookmlModelExploreFieldMapLayerFormat;
(function (LookmlModelExploreFieldMapLayerFormat) {
    LookmlModelExploreFieldMapLayerFormat["Topojson"] = "topojson";
    LookmlModelExploreFieldMapLayerFormat["VectorTileRegion"] = "vector_tile_region";
})(LookmlModelExploreFieldMapLayerFormat = exports.LookmlModelExploreFieldMapLayerFormat || (exports.LookmlModelExploreFieldMapLayerFormat = {}));
