steps:
  # Build the Action Hub container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/actionhub', '.']
  # Push the container to the container registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/actionhub' ]
- name: 'gcr.io/cloud-builders/gcloud'
  # Deploy the container to CloudRun
  # Existing parameters in CloudRun will not be overriden with a deploy unless specified here
  args: [ 'run', 'deploy', 'actionhub', '--image', 'gcr.io/$PROJECT_ID/actionhub', '--region', '${_REGION}', '--platform', 'managed' ]
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
    _REGION: us-central1
images: ['gcr.io/$PROJECT_ID/actionhub']
