"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MparticleEventMaps = exports.MparticleEventTags = exports.MparticleUserMaps = exports.MparticleUserTags = void 0;
var MparticleUserTags;
(function (MparticleUserTags) {
    MparticleUserTags["MpCustomerId"] = "mp_customer_id";
    MparticleUserTags["MpEmail"] = "mp_email";
    MparticleUserTags["MpFacebook"] = "mp_facebook";
    MparticleUserTags["MpGoogle"] = "mp_google";
    MparticleUserTags["MpMicrosoft"] = "mp_microsoft";
    MparticleUserTags["MpTwitter"] = "mp_twitter";
    MparticleUserTags["MpYahoo"] = "mp_yahoo";
    MparticleUserTags["MpOther"] = "mp_other";
    MparticleUserTags["MpOther2"] = "mp_other2";
    MparticleUserTags["MpOther3"] = "mp_other3";
    MparticleUserTags["MpOther4"] = "mp_other4";
})(MparticleUserTags = exports.MparticleUserTags || (exports.MparticleUserTags = {}));
var MparticleUserMaps;
(function (MparticleUserMaps) {
    MparticleUserMaps["Customerid"] = "customerid";
    MparticleUserMaps["Email"] = "email";
    MparticleUserMaps["Facebook"] = "facebook";
    MparticleUserMaps["Google"] = "google";
    MparticleUserMaps["Microsoft"] = "microsoft";
    MparticleUserMaps["Twitter"] = "twitter";
    MparticleUserMaps["Yahoo"] = "yahoo";
    MparticleUserMaps["Other"] = "other";
    MparticleUserMaps["Other2"] = "other2";
    MparticleUserMaps["Other3"] = "other3";
    MparticleUserMaps["Other4"] = "other4";
})(MparticleUserMaps = exports.MparticleUserMaps || (exports.MparticleUserMaps = {}));
var MparticleEventTags;
(function (MparticleEventTags) {
    MparticleEventTags["MpEventName"] = "mp_event_name";
    MparticleEventTags["MpCustomEventType"] = "mp_custom_event_type";
    MparticleEventTags["MpEventId"] = "mp_event_id";
    MparticleEventTags["MpTimestampUnixtimeMs"] = "mp_timestamp_unixtime_ms";
    MparticleEventTags["MpSessionId"] = "mp_session_id";
    MparticleEventTags["MpSessionUuid"] = "mp_session_uuid";
    MparticleEventTags["MpDeviceInfo"] = "mp_device_info";
    MparticleEventTags["MpCustomAttribute"] = "mp_custom_attribute";
})(MparticleEventTags = exports.MparticleEventTags || (exports.MparticleEventTags = {}));
var MparticleEventMaps;
(function (MparticleEventMaps) {
    MparticleEventMaps["EventName"] = "event_name";
    MparticleEventMaps["CustomEventType"] = "custom_event_type";
    MparticleEventMaps["EventId"] = "event_id";
    MparticleEventMaps["TimestampUnixtimeMs"] = "timestamp_unixtime_ms";
    MparticleEventMaps["SessionId"] = "session_id";
    MparticleEventMaps["SessionUuid"] = "session_uuid";
})(MparticleEventMaps = exports.MparticleEventMaps || (exports.MparticleEventMaps = {}));
