export declare const MP_API_URL = "https://inbound.mparticle.com/s2s/v2/bulkevents";
export declare const EVENT_TYPE = "custom_event";
export declare const DEFAULT_EVENT_NAME = "looker_custom_event";
export declare const DEFAULT_CUSTOM_EVENT_TYPE = "other";
export declare const DEV_ENVIRONMENT = "development";
export declare const MAX_EVENTS_PER_BATCH = 100;
export declare const PROD_ENVIRONMENT = "production";
export declare const USER = "user_data";
export declare const EVENT = "event_data";
export declare const VALID_DEVICE_INFO_FIELDS: string[];
