export const MP_API_URL = "https://s2s.mparticle.com/v2/bulkevents/"
export const EVENT_TYPE = "custom_event"
export const DEFAULT_EVENT_NAME = "default_looker_custom_event_name"
export const DEV_ENVIRONMENT = "development"
export const PROD_ENVIRONMENT = "production"
export const USER = "user_data"
export const EVENT = "event_data"
