// This file is automatically generated from the JsonMapper for type DataWebhookPayloadAttachment.
// Modifying the mapper and reloading the page will update this file.

export const REQUEST_DATA_WEBHOOK_PAYLOAD_ATTACHMENT_FIELDS = [

]

export const RESPONSE_DATA_WEBHOOK_PAYLOAD_ATTACHMENT_FIELDS = [
  'mimetype',
  'extension',
  'data'
]

export class RequestDataWebhookPayloadAttachment {

}

export class ResponseDataWebhookPayloadAttachment {
  /** MIME type of the attachment. Ends with ";base64" if the attachment is Base64 encoded. */
  mimetype!: string | null
  /** File extension of the attachment. */
  extension!: string | null
  /** Attachment data. For JSON formats, this JSON is inline. */
  data!: string | null
}

export class WireRequestDataWebhookPayloadAttachment {

}

export class WireResponseDataWebhookPayloadAttachment {
  /** MIME type of the attachment. Ends with ";base64" if the attachment is Base64 encoded. */
  mimetype!: string | null
  /** File extension of the attachment. */
  extension!: string | null
  /** Attachment data. For JSON formats, this JSON is inline. */
  data!: string | null
}
