// This file is automatically generated from the JsonMapper for type DataWebhookPayload.
// Modifying the mapper and reloading the page will update this file.

import { ResponseDataWebhookPayloadScheduledPlan, WireResponseDataWebhookPayloadScheduledPlan } from './data_webhook_payload_scheduled_plan'
import { ResponseDataWebhookPayloadAttachment, WireResponseDataWebhookPayloadAttachment } from './data_webhook_payload_attachment'

export const REQUEST_DATA_WEBHOOK_PAYLOAD_FIELDS = [

]

export const RESPONSE_DATA_WEBHOOK_PAYLOAD_FIELDS = [
  'type',
  'scheduledPlan',
  'attachment',
  'data',
  'formParams'
]

export enum DataWebhookPayloadType {
  Cell = 'cell',
  Query = 'query',
  Dashboard = 'dashboard'
}

export class RequestDataWebhookPayload {

}

export class ResponseDataWebhookPayload {
  /** The type of data payload. Valid values are: "cell", "query", "dashboard". */
  type: DataWebhookPayloadType | null
  /** The associated scheduled plan, if this payload is on a schedule. */
  scheduledPlan: ResponseDataWebhookPayloadScheduledPlan | null
  /** Attached data, if the payload data is a file. */
  attachment: ResponseDataWebhookPayloadAttachment | null
  /** Data, if the payload data is in an inline format. */
  data: {[key: string]: string} | null
  /** Form parameters associated with the payload. */
  formParams: {[key: string]: string} | null
}

export class WireRequestDataWebhookPayload {

}

/* tslint:disable:variable-name */
export class WireResponseDataWebhookPayload {
  /** The type of data payload. Valid values are: "cell", "query", "dashboard". */
  type: DataWebhookPayloadType | null
  /** The associated scheduled plan, if this payload is on a schedule. */
  scheduled_plan: WireResponseDataWebhookPayloadScheduledPlan | null
  /** Attached data, if the payload data is a file. */
  attachment: WireResponseDataWebhookPayloadAttachment | null
  /** Data, if the payload data is in an inline format. */
  data: {[key: string]: string} | null
  /** Form parameters associated with the payload. */
  form_params: {[key: string]: string} | null
}
/* tslint:enable:variable-name */
