// This file is automatically generated from the JsonMapper for type DataWebhookPayloadScheduledPlan.
// Modifying the mapper and reloading the page will update this file.

import { ResponseQuery, WireResponseQuery } from './query'

export const REQUEST_DATA_WEBHOOK_PAYLOAD_SCHEDULED_PLAN_FIELDS = [

]

export const RESPONSE_DATA_WEBHOOK_PAYLOAD_SCHEDULED_PLAN_FIELDS = [
  'scheduledPlanId',
  'title',
  'type',
  'url',
  'queryId',
  'query',
  'filtersDifferFromLook'
]

export enum DataWebhookPayloadScheduledPlanType {
  Look = 'Look',
  Dashboard = 'Dashboard'
}

export class RequestDataWebhookPayloadScheduledPlan {

}

export class ResponseDataWebhookPayloadScheduledPlan {
  /** ID of the scheduled plan */
  scheduledPlanId: number | null
  /** Title of the scheduled plan. */
  title: string | null
  /** Type of content of the scheduled plan. Valid values are: "Look", "Dashboard". */
  type: DataWebhookPayloadScheduledPlanType
  /** URL of the content item in Looker. */
  url: string | null
  /** ID of the query that the data payload represents. */
  queryId: number | null
  /** Query that was run (not available for dashboards) */
  query: ResponseQuery | null
  /** A boolean representing whether this schedule payload has customized the filter values compared to the underlying content item. */
  filtersDifferFromLook: boolean
}

export class WireRequestDataWebhookPayloadScheduledPlan {

}

/* tslint:disable:variable-name */
export class WireResponseDataWebhookPayloadScheduledPlan {
  /** ID of the scheduled plan */
  scheduled_plan_id: number | null
  /** Title of the scheduled plan. */
  title: string | null
  /** Type of content of the scheduled plan. Valid values are: "Look", "Dashboard". */
  type: DataWebhookPayloadScheduledPlanType
  /** URL of the content item in Looker. */
  url: string | null
  /** ID of the query that the data payload represents. */
  query_id: number | null
  /** Query that was run (not available for dashboards) */
  query: WireResponseQuery | null
  /** A boolean representing whether this schedule payload has customized the filter values compared to the underlying content item. */
  filters_differ_from_look: boolean
}
/* tslint:enable:variable-name */
