// This file is automatically generated from the JsonMapper for type Integration.
// Modifying the mapper and reloading the page will update this file.

import { RequestIntegrationParam, ResponseIntegrationParam, WireRequestIntegrationParam, WireResponseIntegrationParam } from './integration_param'
import { ResponseIntegrationRequiredField, WireResponseIntegrationRequiredField } from './integration_required_field'

export const REQUEST_INTEGRATION_FIELDS = [
  'enabled',
  'params'
]

export const RESPONSE_INTEGRATION_FIELDS = [
  'id',
  'integrationHubId',
  'label',
  'description',
  'enabled',
  'params',
  'supportedFormats',
  'supportedActionTypes',
  'supportedFormattings',
  'supportedVisualizationFormattings',
  'iconUrl',
  'requiredFields',
  'can'
]

export enum IntegrationSupportedActionTypes {
  Cell = 'cell',
  Query = 'query',
  Dashboard = 'dashboard'
}

export enum IntegrationSupportedFormats {
  Txt = 'txt',
  Csv = 'csv',
  InlineJson = 'inline_json',
  Json = 'json',
  JsonDetail = 'json_detail',
  Xlsx = 'xlsx',
  Html = 'html',
  CsvZip = 'csv_zip',
  WysiwygPdf = 'wysiwyg_pdf',
  AssembledPdf = 'assembled_pdf',
  WysiwygPng = 'wysiwyg_png'
}

export enum IntegrationSupportedFormattings {
  Formatted = 'formatted',
  Unformatted = 'unformatted'
}

export enum IntegrationSupportedVisualizationFormattings {
  Apply = 'apply',
  Noapply = 'noapply'
}

export class RequestIntegration {
  /** Whether the integration is available to users. */
  enabled?: boolean
  /** Array of params for the integration. */
  params?: RequestIntegrationParam[]
}

export class ResponseIntegration {
  /** ID of the integration. */
  id!: string
  /** ID of the integration hub. */
  integrationHubId!: number
  /** Label for the integration. */
  label!: string
  /** Description of the integration. */
  description!: string | null
  /** Whether the integration is available to users. */
  enabled!: boolean
  /** Array of params for the integration. */
  params!: ResponseIntegrationParam[]
  /** A list of data formats the integration supports. Valid values are: "txt", "csv", "inline_json", "json", "json_detail", "xlsx", "html", "csv_zip", "wysiwyg_pdf", "assembled_pdf", "wysiwyg_png". */
  supportedFormats!: IntegrationSupportedFormats[]
  /** A list of action types the integration supports. Valid values are: "cell", "query", "dashboard". */
  supportedActionTypes!: IntegrationSupportedActionTypes[]
  /** A list of formatting options the integration supports. Valid values are: "formatted", "unformatted". */
  supportedFormattings!: IntegrationSupportedFormattings[]
  /** A list of visualization formatting options the integration supports. Valid values are: "apply", "noapply". */
  supportedVisualizationFormattings!: IntegrationSupportedVisualizationFormattings[]
  /** URL to an icon for the integration. */
  iconUrl!: string | null
  /** A list of descriptions of required fields that this integration is compatible with. If there are multiple entries in this list, the integration requires more than one field. */
  requiredFields!: ResponseIntegrationRequiredField[]
  /** Operations the current user is able to perform on this object */
  can!: { [key: string]: boolean }
}

export class WireRequestIntegration {
  /** Whether the integration is available to users. */
  enabled?: boolean
  /** Array of params for the integration. */
  params?: WireRequestIntegrationParam[]
}

/* tslint:disable:variable-name */
export class WireResponseIntegration {
  /** ID of the integration. */
  id!: string
  /** ID of the integration hub. */
  integration_hub_id!: number
  /** Label for the integration. */
  label!: string
  /** Description of the integration. */
  description!: string | null
  /** Whether the integration is available to users. */
  enabled!: boolean
  /** Array of params for the integration. */
  params!: WireResponseIntegrationParam[]
  /** A list of data formats the integration supports. Valid values are: "txt", "csv", "inline_json", "json", "json_detail", "xlsx", "html", "csv_zip", "wysiwyg_pdf", "assembled_pdf", "wysiwyg_png". */
  supported_formats!: IntegrationSupportedFormats[]
  /** A list of action types the integration supports. Valid values are: "cell", "query", "dashboard". */
  supported_action_types!: IntegrationSupportedActionTypes[]
  /** A list of formatting options the integration supports. Valid values are: "formatted", "unformatted". */
  supported_formattings!: IntegrationSupportedFormattings[]
  /** A list of visualization formatting options the integration supports. Valid values are: "apply", "noapply". */
  supported_visualization_formattings!: IntegrationSupportedVisualizationFormattings[]
  /** URL to an icon for the integration. */
  icon_url!: string | null
  /** A list of descriptions of required fields that this integration is compatible with. If there are multiple entries in this list, the integration requires more than one field. */
  required_fields!: WireResponseIntegrationRequiredField[]
  /** Operations the current user is able to perform on this object */
  can!: { [key: string]: boolean }
}
/* tslint:enable:variable-name */
