// This file is automatically generated from the JsonMapper for type IntegrationParam.
// Modifying the mapper and reloading the page will update this file.

export const REQUEST_INTEGRATION_PARAM_FIELDS = [
  'value',
  'userAttributeName'
]

export const RESPONSE_INTEGRATION_PARAM_FIELDS = [
  'name',
  'label',
  'description',
  'required',
  'hasValue',
  'value',
  'userAttributeName',
  'sensitive'
]

export class RequestIntegrationParam {
  /** The current value of the parameter. Always null if the value is sensitive. When writing, null values will be ignored. Set the value to an empty string to clear it. */
  value?: string | null
  /** When present, the param's value comes from this user attribute instead of the 'value' parameter. Set to null to use the 'value'. */
  userAttributeName?: string | null
}

export class ResponseIntegrationParam {
  /** Name of the parameter. */
  name: string | null
  /** Label of the parameter. */
  label: string | null
  /** Short description of the parameter. */
  description: string | null
  /** Whether the parameter is required to be set to use the destination. */
  required: boolean
  /** Whether the parameter has a value set. */
  hasValue: boolean
  /** The current value of the parameter. Always null if the value is sensitive. When writing, null values will be ignored. Set the value to an empty string to clear it. */
  value: string | null
  /** When present, the param's value comes from this user attribute instead of the 'value' parameter. Set to null to use the 'value'. */
  userAttributeName: string | null
  /** Whether the parameter contains sensitive data like API credentials. */
  sensitive: boolean
}

/* tslint:disable:variable-name */
export class WireRequestIntegrationParam {
  /** The current value of the parameter. Always null if the value is sensitive. When writing, null values will be ignored. Set the value to an empty string to clear it. */
  value?: string | null
  /** When present, the param's value comes from this user attribute instead of the 'value' parameter. Set to null to use the 'value'. */
  user_attribute_name?: string | null
}
/* tslint:enable:variable-name */

/* tslint:disable:variable-name */
export class WireResponseIntegrationParam {
  /** Name of the parameter. */
  name: string | null
  /** Label of the parameter. */
  label: string | null
  /** Short description of the parameter. */
  description: string | null
  /** Whether the parameter is required to be set to use the destination. */
  required: boolean
  /** Whether the parameter has a value set. */
  has_value: boolean
  /** The current value of the parameter. Always null if the value is sensitive. When writing, null values will be ignored. Set the value to an empty string to clear it. */
  value: string | null
  /** When present, the param's value comes from this user attribute instead of the 'value' parameter. Set to null to use the 'value'. */
  user_attribute_name: string | null
  /** Whether the parameter contains sensitive data like API credentials. */
  sensitive: boolean
}
/* tslint:enable:variable-name */
