// This file is automatically generated based on the Looker Core API metadata.

export interface LookmlModelExploreFieldEnumeration {
  /** Label */
  label: string | null
  /** Value */
  value: string | number | null
}

export interface RequestLookmlModelExploreFieldEnumeration {

}
