// This file is automatically generated based on the Looker Core API metadata.

export interface LookmlModelExploreFieldMeasureFilters {
  /** Filter field name */
  field: string | null
  /** Filter condition value */
  condition: string | null
}

export interface RequestLookmlModelExploreFieldMeasureFilters {

}
