// This file is automatically generated based on the Looker Core API metadata.

export interface LookmlModelExploreFieldSqlCase {
  /** SQL Case label value */
  value: string | null
  /** SQL Case condition expression */
  condition: string | null
}

export interface RequestLookmlModelExploreFieldSqlCase {

}
