import * as Hub from "../../hub";
export declare class AugerTrainAction extends Hub.Action {
    name: string;
    label: string;
    iconName: string;
    description: string;
    supportedActionTypes: Hub.ActionType[];
    supportedFormattings: Hub.ActionFormatting[];
    supportedVisualizationFormattings: Hub.ActionVisualizationFormatting[];
    requiredFields: never[];
    usesStreaming: boolean;
    executeInOwnProcess: boolean;
    extendedAction: boolean;
    params: {
        name: string;
        label: string;
        description: string;
        required: boolean;
        sensitive: boolean;
    }[];
    minimumSupportedLookerVersion: string;
    supportedFormats: (request: Hub.ActionRequest) => Hub.ActionFormat[];
    execute(request: Hub.ActionRequest): Promise<Hub.ActionResponse>;
    form(request: Hub.ActionRequest): Promise<Hub.ActionForm>;
    private validateAugerToken;
    private getProjectFileURL;
    private chunkToS3;
    private processStream;
    private formatFields;
    private formatRecords;
    private uploadToS3;
    private startProject;
    private startProjectFile;
    private startExperiment;
    private createProjectFile;
    private createExperiment;
    private getProjectFile;
    private getProject;
    private startSession;
    private formatModelSettings;
    private startPoller;
    private prettyAugerError;
    private formatParams;
    private validateParams;
}
