name: Actions CI
on:
  pull_request:
    branches:
      - main
      - master

  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Install dependencies
        run: |
          yarn
          yarn build

      - name: Run unit tests
        run: yarn test
